## 3. Matrix Multiplication
Let's learn basics of matrix multiplication

In [1]:
import numpy as np

In [3]:
rev = np.array([[100, 200, 220], [24, 36, 40], [12, 18, 20]])
exp = np.array([[80, 90, 100], [10, 16, 20], [6, 10, 10]])

In [5]:
rev

array([[100, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [6]:
exp

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  6,  10,  10]])

In [4]:
profit = rev - exp # you can just subtract using numpy array
profit

array([[ 20, 110, 120],
       [ 14,  20,  20],
       [  6,   8,  10]])

In [7]:
price_p_unit = np.array([1000, 400, 1200])
units = np.array([[30, 40, 50], [5, 10, 15], [2, 5, 7]])

In [9]:
price_p_unit*units # if we multiply, it automatically expands the first array 
# as if [[1000, 400, 1200], [1000, 400, 1200], [1000, 400, 1200]]

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [11]:
# Then, we need dot product
np.dot(price_p_unit, units)

array([34400, 50000, 64400])