## 8. GPU benchmark
ALU (arithmetic logic unit) computes the arithmetic calculation, and CPU has only one ALU. On the other hand, GPU contains several ALUs, which gave GPU higher computing power. Plus, GPU cannot compute complicated computation compared to CPU, which is okay since deep learning usually builds up multiple layers for simple calculation instead of single complicated calculation. 

In [15]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [16]:
tf.config.experimental.list_physical_devices() # right now, only CPU is available. I need to install CUDA toolkit and cuDNN

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

To apply GPU, we need CUDA Toolkit and cuDNN. The instructions are guided in the link below, and the application versions are written for reference. 

In [17]:
# https://shawnhymel.com/1961/how-to-install-tensorflow-with-gpu-support-on-windows/
# version: tensorflow 2.6.0 , Cudnn7.6.5 and Cuda 10.1 , python 3.8

In [18]:
print(tf.__version__)

2.6.0


In [19]:
tf.test.is_built_with_cuda()

True

In [20]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()

In [21]:
X_train.shape

(50000, 32, 32, 3)

In [22]:
X_train[0][0]

array([[ 59,  62,  63],
       [ 43,  46,  45],
       [ 50,  48,  43],
       [ 68,  54,  42],
       [ 98,  73,  52],
       [119,  91,  63],
       [139, 107,  75],
       [145, 110,  80],
       [149, 117,  89],
       [149, 120,  93],
       [131, 103,  77],
       [125,  99,  76],
       [142, 115,  91],
       [144, 112,  86],
       [137, 105,  79],
       [129,  97,  71],
       [137, 106,  79],
       [134, 106,  76],
       [124,  97,  64],
       [139, 113,  78],
       [139, 112,  75],
       [133, 105,  69],
       [136, 105,  74],
       [139, 108,  77],
       [152, 120,  89],
       [163, 131, 100],
       [168, 136, 108],
       [159, 129, 102],
       [158, 130, 104],
       [158, 132, 108],
       [152, 125, 102],
       [148, 124, 103]], dtype=uint8)

In [23]:
y_train.shape

(50000, 1)

In [24]:
y_train[0:5] # ex. 6 = frog

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [25]:
def plot_sample(index):
    plt.figure(figsize = (10,1))
    plt.imshow(X_train[index])

In [28]:
plot_sample # we can see the image of a frog!

<function __main__.plot_sample(index)>

In [31]:
classes = ['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']

In [32]:
classes[y_train[3][0]]

'deer'

In [44]:
X_train_scaled = X_train/255 # normalize it to 0~1
X_test_scaled = X_test/255

In [45]:
X_train_scaled.shape

(50000, 32, 32, 3)

In [46]:
y_train[:5] # these are not in one-hot encoding! 

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [47]:
y_train_categorical = keras.utils.to_categorical(
    y_train, num_classes = 10, dtype = 'float32'
)

y_train_categorical # in one-hot encoding

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [48]:
y_test_categorical = keras.utils.to_categorical(
    y_test, num_classes = 10, dtype = 'float32'
)

In [49]:
X_train.shape

(50000, 32, 32, 3)

In [50]:
X_train_scaled.shape

(50000, 32, 32, 3)

In [51]:
32*32*3 # the size of flatten layer

3072

In [52]:
y_train_categorical.shape

(50000, 10)

In [53]:
# ANN 
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)), # flatten layer
    keras.layers.Dense(3000, activation = 'relu'), # hidden layer
    keras.layers.Dense(1000, activation = 'relu'), # hidden layer, the nodes are randomly given
    keras.layers.Dense(10, activation = 'sigmoid') # output layer  
])

model.compile(optimizer='SGD',
             loss = 'categorical_crossentropy', # for one-hot encoding 
              # (if it is in 0, 1, 2, .. , 9 then, sparse_categorical_crossentropy)
             metrics = ['accuracy'])

model.fit(X_train_scaled, y_train_categorical, epochs=50)

Epoch 1/50
1563/1563 [==============================] - 46s 29ms/step - loss: 1.8098 - accuracy: 0.3544
Epoch 2/50
1563/1563 [==============================] - 54s 34ms/step - loss: 1.6244 - accuracy: 0.4297
Epoch 3/50
1563/1563 [==============================] - 77s 49ms/step - loss: 1.5424 - accuracy: 0.4556
Epoch 4/50
1563/1563 [==============================] - 62s 39ms/step - loss: 1.4811 - accuracy: 0.4798
Epoch 5/50
1563/1563 [==============================] - 70s 45ms/step - loss: 1.4315 - accuracy: 0.4953
Epoch 6/50
1563/1563 [==============================] - 56s 36ms/step - loss: 1.3890 - accuracy: 0.5121
Epoch 7/50
1563/1563 [==============================] - 73s 46ms/step - loss: 1.3522 - accuracy: 0.5268
Epoch 8/50
1563/1563 [==============================] - 60s 38ms/step - loss: 1.3164 - accuracy: 0.5394
Epoch 9/50
1563/1563 [==============================] - 65s 41ms/step - loss: 1.2827 - accuracy: 0.5519
Epoch 10/50
1563/1563 [==============================] - 64s 41m

GPU could speed up the training, compared to CPU. 

In [54]:
model.predict(X_test_scaled)

array([[6.04674339e-01, 7.68483639e-01, 8.09397101e-01, ...,
        2.21520662e-04, 4.30237234e-01, 1.12865329e-01],
       [6.17319465e-01, 9.94368672e-01, 2.18189955e-01, ...,
        1.57954186e-01, 9.99939203e-01, 9.77783561e-01],
       [9.19405758e-01, 9.29981232e-01, 2.70354927e-01, ...,
        7.22154915e-01, 9.97179866e-01, 9.33674455e-01],
       ...,
       [3.26844662e-01, 8.39084387e-04, 9.97206032e-01, ...,
        8.60554695e-01, 1.33588433e-01, 3.77821922e-03],
       [7.52315223e-02, 4.54149753e-01, 9.43706870e-01, ...,
        3.08062136e-02, 6.50046468e-02, 8.05360079e-03],
       [1.29635274e-01, 2.46057808e-02, 8.71749699e-01, ...,
        9.93077636e-01, 1.16455495e-01, 2.56009400e-01]], dtype=float32)

In [55]:
np.argmax(model.predict(X_test_scaled)[0]) # need to use maximum value for the answer 

3

In [56]:
classes[np.argmax(model.predict(X_test_scaled)[0])] # need to use maximum value for the answer 

'cat'

In [57]:
y_test[0]

array([3], dtype=uint8)

In [58]:
classes[y_test[0][0]]

'cat'

In [59]:
model.evaluate(X_test_scaled, y_test_categorical)

313/313 [==============================] - 7s 20ms/step - loss: 1.5627 - accuracy: 0.5638


[1.5626628398895264, 0.5637999773025513]

In [60]:
def get_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(32,32,3)), # flatten layer
        keras.layers.Dense(3000, activation = 'relu'), # hidden layer
        keras.layers.Dense(1000, activation = 'relu'), # hidden layer, the nodes are randomly given
        keras.layers.Dense(10, activation = 'sigmoid') # output layer  
    ])
    
    model.compile(optimizer='SGD',
             loss = 'categorical_crossentropy', # for one-hot encoding 
              # (if it is in 0, 1, 2, .. , 9 then, sparse_categorical_crossentropy)
             metrics = ['accuracy'])
    
    return model